# Generated by Django 4.0.4 on 2022-04-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_description', models.TextField()),
                ('bonuses', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('health_dice', models.CharField(max_length=45)),
                ('max_health', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('surrname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('idweapon', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_of_weapon', models.CharField(max_length=45)),
                ('type_of_weapon', models.CharField(choices=[('axe', 'axe'), ('sword', 'sword'), ('bow', 'bow'), ('knife', 'knife'), ('mace', 'mace'), ('spear', 'spear'), ('crossbow', 'crossbow'), ('stick', 'stick')], default='axe', max_length=45)),
                ('damage', models.CharField(default='2x4d', max_length=20)),
                ('damage_type', models.CharField(choices=[('bludgeoning', 'bludgeoning'), ('fire', 'fire'), ('radiant', 'radiant'), ('cold', 'cold'), ('slashing', 'slashing')], default='fire', max_length=45)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='character',
            name='dnd_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.class'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.level'),
        ),
        migrations.AddField(
            model_name='character',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.player'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.weapons'),
        ),
    ]
