# Generated by Django 4.0.4 on 2022-04-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_character_class_level_player_skills_weapons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_has_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.class')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.skills')),
            ],
        ),
    ]
