# Generated by Django 4.0.4 on 2022-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_class_has_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['character_name']},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['class_name']},
        ),
        migrations.AlterModelOptions(
            name='class_has_skills',
            options={'ordering': ['class_name']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['level']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['lastname', 'surrname']},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['skill_name']},
        ),
        migrations.AlterModelOptions(
            name='weapons',
            options={'ordering': ['type_of_weapon']},
        ),
        migrations.AddField(
            model_name='class',
            name='class_picture',
            field=models.ImageField(default='NULL', upload_to='static/img/'),
        ),
    ]
