# Generated by Django 4.0.4 on 2022-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_character_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_picture',
            field=models.ImageField(default='NULL', upload_to='polls/static/img/'),
        ),
    ]
