# Generated by Django 4.0.4 on 2022-05-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_class_class_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_image',
            field=models.ImageField(default='NULL', upload_to='polls/static/media/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.player', verbose_name='Name of the player'),
        ),
        migrations.AlterField(
            model_name='class_has_skills',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.class', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='class_has_skills',
            name='skill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.skills', verbose_name='Skills'),
        ),
    ]
