# Generated by Django 4.0.4 on 2022-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_character_character_image_alter_character_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_image',
            field=models.ImageField(default='NULL', upload_to='character_path'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_picture',
            field=models.ImageField(default='NULL', upload_to='class_path'),
        ),
    ]
