# Generated by Django 4.0.4 on 2022-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_character_character_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_background',
            field=models.TextField(default='Žebrák', verbose_name='Background story'),
        ),
    ]
