# Generated by Django 4.0.4 on 2022-06-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_character_character_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='skill_id',
            field=models.ManyToManyField(to='polls.skills', verbose_name='Skills'),
        ),
    ]
