# Generated by Django 4.0.4 on 2022-06-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_class_skill_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_has_Skills',
        ),
    ]
