# Generated by Django 4.0.4 on 2022-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_delete_class_has_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_picture',
            field=models.ImageField(default='NULL', upload_to='player_path'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_background',
            field=models.TextField(default='Homeless', verbose_name='Background story'),
        ),
    ]
