# Generated by Django 4.0.4 on 2022-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_player_player_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_picture',
            field=models.ImageField(default='avatar.png', upload_to='player_path'),
        ),
    ]
